title: "MXIMP's Blog"
remote_theme: pages-themes/hacker@v0.2.0
url: https://mximp.github.io/
baseurl: /mximp/
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
